spring:
  h2:
    console:
      enabled: true
logging:
  level:
    com.ing.switchtojava: DEBUG
    org.spring.framework.jdbc: DEBUG
    org.spring.framework.data: DEBUG
    com.zaxxer.hikari: DEBUG
