spring:
  h2:
    console:
      enabled: true
  jpa:
      show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
logging:
  level:
    com.ing.switchtojava: ERROR
    org.springframework.data: DEBUG
    #org.springframework.security: DEBUG